default interface outbound-mysql {
    use pkg.mysql-types.{mysql-error}
    use pkg.rdbms-types.{row-set, parameter-value}

    // query the database: select
    query: func(address: string, statement: string, params: list<parameter-value>) -> result<row-set, mysql-error>

    // execute command to the database: insert, update, delete
    execute: func(address: string, statement: string, params: list<parameter-value>) -> result<_, mysql-error>
}
