use * from redis-types

// Publish a Redis message to the specificed channel and return an error, if any.
publish: func(address: string, channel: string, payload: payload) -> expected<unit, error>

// Get the value of a key.
get: func(address: string, key: string) -> expected<payload, error>

// Set key to value. If key alreads holds a value, it is overwritten.
set: func(address: string, key: string, value: payload) -> expected<unit, error>

// Increments the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation.
// An error is returned if the key contains a value of the wrong type or contains a string that can not be represented as integer.
incr: func(address: string, key: string) -> expected<s64, error>
