default interface outbound-pg {
    use pkg.pg-types.{pg-error}
    use pkg.rdbms-types.{row-set, parameter-value}

    // query the database: select
    query: func(address: string, statement: string, params: list<parameter-value>) -> result<row-set, pg-error>

    // execute command to the database: insert, update, delete
    execute: func(address: string, statement: string, params: list<parameter-value>) -> result<u64, pg-error>
}
