// A simple cache interface.

use * from types

// Set the payload for the given key.
// Implementations may choose to ignore the time-to-live (in seconds) argument.
// TODO (@radu-matei): perhaps return the number of bytes written?
set: function(key: string, value: payload, ttl: option<u32>) -> expected<_, error>

// Get the payload stored in the cache for the given key.
// If not found, return a success result with an empty payload.
get: function(key: string) -> expected<payload, error>

// Delete the cache entry for the given key.
delete: function(key: string) -> expected<_, error>
