// Log levels.
enum level {
    trace,
    debug,
    info,
    warn,
    error,
    fatal
}

// General log function.
log: func(msg: string, lvl: level)

// Specialized log functions.
trace: func(msg: string)
debug: func(msg: string)
info: func(msg: string)
warn: func(msg: string)
error: func(msg: string)
fatal: func(msg: string)
