// General purpose error.
// TODO: We can provide richer info than this: https://docs.rs/mysql/latest/mysql/error/enum.Error.html
variant mysql-error {
    success,
    connection-failed(string),
    bad-parameter(string),
    query-failed(string),
    value-conversion-failed(string),
    other-error(string)
}
