package fermyon:spin-virt;

world deny-all {
    export wasi:cli/environment@0.2.0;
    export wasi:filesystem/preopens@0.2.0;
    export wasi:http/outgoing-handler@0.2.0;
    export wasi:sockets/ip-name-lookup@0.2.0;
    export wasi:sockets/tcp-create-socket@0.2.0;
    export wasi:sockets/tcp@0.2.0;
    export wasi:sockets/udp-create-socket@0.2.0;
    export wasi:sockets/udp@0.2.0;

    export fermyon:spin/llm@2.0.0;
    export fermyon:spin/redis@2.0.0;
    export fermyon:spin/mqtt@2.0.0;
    export fermyon:spin/rdbms-types@2.0.0;
    export fermyon:spin/postgres@2.0.0;
    export fermyon:spin/mysql@2.0.0;
    export fermyon:spin/sqlite@2.0.0;
    export fermyon:spin/key-value@2.0.0;
    export fermyon:spin/variables@2.0.0;
}
