default world trigger-http {
  import config: spin.config
  import postgres: spin.postgres
  import mysql: spin.mysql
  import sqlite: spin.sqlite
  import redis: spin.redis
  import key-value: spin.key-value
  import http: spin.http
  export inbound-http: spin.inbound-http
}
