default world trigger-redis {
  import config: spin.config
  import postgres: spin.postgres
  import mysql: spin.mysql
  import sqlite: spin.sqlite
  import redis: spin.redis
  import key-value: spin.key-value
  import http: spin.http
  export inbound-redis: spin.inbound-redis
}
