package fermyon:spin@2.0.0

world host {
  include fermyon:spin/host
  include platform
}

world redis-trigger {
  include platform
  export fermyon:spin/inbound-redis
}

world http-trigger {
  include platform
  export fermyon:spin/inbound-http
}

world platform {
  import fermyon:spin/config
  import fermyon:spin/http
  import fermyon:spin/mysql
  import fermyon:spin/llm
  import wasi:http/types
  import wasi:http/outgoing-handler

  import redis
  import postgres
  import sqlite
  import key-value
}
