default world spin-timer {
  // Timer execution loop exit variant
  variant continue-timer {      
      true,
      false
  }

  // Get the value of a key.
  export handle-timer-request: func() -> continue-timer
}
