package fermyon:spin

world reactor-imports {
  import config
  import postgres
  import mysql
  import sqlite
  import redis
  import key-value
  import http
  import llm
}

world reactor-wasi-http {
  import wasi:http/outgoing-handler
  export wasi:http/incoming-handler
}

world reactor-http-export {
  export inbound-http
}

world reactor-redis-export {
  export inbound-redis
}

world reactor-exports {
  export inbound-http
  export inbound-redis
}

world reactor {
  include reactor-imports
  include reactor-exports
}

world redis-trigger {
  include reactor-imports
  export inbound-redis
}

world http-trigger {
  include reactor-imports
  export inbound-http
}
