interface inbound-redis {
    // The entrypoint for a Redis handler.
    handle-message: func(message: payload) -> result<_, error>

    // The message payload.
    type payload = list<u8>

    // General purpose error.
    enum error {
        success,
        error,
    }
} 

default world spin-redis {
    export inbound-redis: self.inbound-redis
}