package fermyon:spin

world http-trigger {
  export inbound-http
}

world redis-trigger {
  export inbound-redis
}

world wasi-http-trigger {
  import wasi:http/outgoing-handler
  export wasi:http/incoming-handler
}
